# Generated by Django 4.0.2 on 2022-06-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('head0', models.CharField(default='', max_length=100)),
                ('chead0', models.CharField(default='No Content added', max_length=5000)),
                ('head1', models.CharField(default='', max_length=100)),
                ('chead1', models.CharField(default='No Content added', max_length=5000)),
                ('head2', models.CharField(default='', max_length=100)),
                ('chead2', models.CharField(default='No Content added', max_length=5000)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
