# Generated by Django 4.0.2 on 2022-05-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
