# Generated by Django 4.0.2 on 2022-05-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=800)),
            ],
        ),
    ]
