# Generated by Django 4.0.2 on 2022-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_orders_zipcode_orders_phone_orders_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0)),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
