# Generated by Django 4.0.2 on 2022-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_update_alter_orders_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_update',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
